export const shuffleAllTracksSelector = (store) => store.track.shuffleAllTracks
export const allTracksSelector = (store) => store.track.allTracks
export const shuffleSelector = (store) => store.track.shuffle
export const setSelectedSong = (store) => store.track.selectedSong
export const setIsPlaying = (store) => store.track.isPlaying
export const setIsLiked = (store) => store.track.isliked
export const setIsLikedIds = (store) => store.track.isLikedIds
export const setFullToken = (store) => store.auth.token
export const setUser = (store) => store.auth.user
